name: videotrade_app
description: "A App all about trading videogames"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_ui_auth: ^3.0.1
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
